### ISSUE TITLE
Error during NPM instalation.

### ISSUE THREAD

**Issue by FishTFM** [ekelokorpi/panda.js#126]
Hello,
today I tried to install Panda via NPM but at the end of the downloading state I got an error.

```log
C:\Users\user\AppData\Roaming\npm\panda -> C:\Users\user\AppData\Roaming\npm\nod
e_modules\pandatool\panda.js
pandatool@1.10.2 C:\Users\user\AppData\Roaming\npm\node_modules\pandatool
├── node-watch@0.3.4
├── open@0.0.5
├── colors@0.6.2
├── uglify-js@2.4.16 (async@0.2.10, uglify-to-browserify@1.0.2, optimist@0.3.7,
source-map@0.1.34)
├── boilerplate@0.1.5 (underscore@1.4.4, wrench@1.4.4, commander@1.1.1, handleba
rs@1.0.12)
├── jscs@1.3.0 (strip-json-comments@0.1.1, vow@0.3.9, colors@0.6.0-1, esprima@1.
0.3, commander@1.2.0, glob@3.2.7, xmlbuilder@1.1.2, minimatch@0.2.12, vow-fs@0.2
.3)
├── download@0.1.19 (get-stdin@0.1.0, get-urls@0.1.2, mkdirp@0.3.5, each-async@0
.1.3, nopt@2.2.1, through2@0.4.2, decompress@0.2.5, request@2.53.0)
├── imagemin@3.1.0 (get-stdin@3.0.2, optional@0.1.2, stream-combiner@0.2.1, viny
l@0.4.6, meow@2.1.0, through2@0.6.3, concat-stream@1.4.7, vinyl-fs@0.3.13, image
min-svgo@4.1.0)
└── express@3.4.8 (merge-descriptors@0.0.1, debug@0.8.1, fresh@0.2.0, methods@0.
1.0, range-parser@0.0.4, buffer-crc32@0.2.1, cookie-signature@1.0.1, cookie@0.1.
0, mkdirp@0.3.5, commander@1.3.2, send@0.1.4, connect@2.12.0)
npm ERR! Error: Callback called more than once.
npm ERR!     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils
\error-handler.js:80:16)
npm ERR!     at save (C:\Program Files\nodejs\node_modules\npm\lib\install.js:33
6:12)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:101:7
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:194:5
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-insta
lled\read-installed.js:130:5
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-insta
lled\read-installed.js:258:14
npm ERR!     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\
lib\async-map.js:48:11)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-insta
lled\read-installed.js:258:14
npm ERR!     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\
lib\async-map.js:48:11)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-insta
lled\read-installed.js:258:14
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "pandatool"
npm ERR! cwd C:\Users\user\Developpement\PHP\Projets\BlobsWar\prototype-02
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
```

**Comment by FishTFM** [comment]
Tried a panda install and get it working, but what is that stupid error ? :octopus:

**Comment by ekelokorpi** [comment]
Try updating your npm, seems to be old version.

**Comment by ekelokorpi** [comment]
What OS are you using?

**Comment by FishTFM** [comment]
Windows 8 64 bits

**Comment by ekelokorpi** [comment]
So you got it working?
